### ISSUE TITLE
Cannot load Mathfield

### ISSUE THREAD

**Issue by alexandrmiee** [arnog/vue-mathlive#1]
I install MathLive 

`npm install mathlive `

Then try to add its in vue main.js file
```
import MathLive from "mathlive";
import Mathfield from "mathlive/vue-mathlive";
Vue.use(Mathfield, MathLive);
```
Result
```
This dependency was not found:
* mathlive/vue-mathlive in ./src/main.js
```

If I use dist folder

```
import MathLive from "mathlive/dist/mathlive";
import Mathfield from "mathlive/dist/vue-mathlive.mjs";
```

Then I get error

`You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

**Comment by arnog** [comment]
At this point web browsers do not support module path without an extension. So, try:
```javascript
import MathLive from "mathlive.js";
import Mathfield from "mathlive/vue-mathlive.mjs";
Vue.use(Mathfield, MathLive);
```
Adjust the path as necessary to point where you have installed MathLive, but do make sure to include the appropriate extensions for both modules.

**Comment by alexandrmiee** [comment]
Still get the error

`You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

**Comment by arnog** [comment]
It looks like you're having some Vue configuration issue. I would recommend reading and following the suggestions from this article: https://medium.com/@stefanledin/solve-the-you-are-using-the-runtime-only-build-of-vue-error-e675031f2c50

**Comment by Mohitpokra** [comment]
I am using this in "main.js" file

import MathLive from "mathlive/dist/mathlive";
import Mathfield from "mathlive/dist/vue-mathlive";
Vue.use(Mathfield, MathLive);

my component code includes
<mathlive-mathfield 
            id='mf' 
            ref="mathfield" 
            :config="{smartFence:false}"
            @focus="ping"
            :on-keystroke="displayKeystroke"
            v-model="formula">f(x)=</mathlive-mathfield>

Formula value is  "x=-b\\pm \\frac {\\sqrt{b^2-4ac}}{2a}". still it is not rendering maths equation.

Can anyone help where I am going wrong?
