### ISSUE TITLE
Bug with Vue wrapper component

### ISSUE THREAD

**Issue by leontepe** [arnog/vue-mathlive#14]
I think the Vue component for MathLive is not working properly. I am trying to implement a custom wrapper component for the MathLive mathfield, like so:

```
Vue.component('mathfield', {
  props: ['value'],
  template: `
    <mathlive-mathfield
       v-bind:value="value"
       v-on:input="$emit('input', $event.target.value)"
     ></mathlive-mathfield>
  `
})
```

which I read on the [documentation concering custom components](https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components), so I think this would be the right way to do it in terms of Vue.

What happens now is that the changes are not propagated to the root and it shows the following errors in the console:

```
vue.js:634 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'value' of undefined"

found in

---> <MathliveMathfield>
       <Mathfield>
         <Root>
```

... and ...

```
vue.js:1897 TypeError: Cannot read property 'value' of undefined
    at input (eval at createFunction (vue.js:11649), <anonymous>:3:131)
    at invokeWithErrorHandling (vue.js:1863)
    at VueComponent.invoker (vue.js:2188)
    at invokeWithErrorHandling (vue.js:1863)
    at VueComponent.Vue.$emit (vue.js:3889)
    at VueComponent.Vue.<computed> [as $emit] (backend.js:1793)
    at Object.onContentDidChange (vue-mathlive.js:92)
    at pr._onContentDidChange (mathlive.mjs:2)
    at Object.onContentDidChange (mathlive.mjs:2)
    at Kt (mathlive.mjs:2)
```

The same implementation, but with a standard `<input>` tag, works fine:
```
Vue.component('mathfield', {
  props: ['value'],
  template: `
    <input
       v-bind:value="value"
       v-on:input="$emit('input', $event.target.value)"
     ></input>
  `
})
```

Addition: When using a standard v-model in the custom wrapper component a different error message pops up:
```
Vue.component('mathfield', {
  props: ['value'],
  template: `
    <mathlive-mathfield
       v-model="value"
     ></mathlive-mathfield>
  `
})
```
```
vue.js:634 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"

found in

---> <Mathfield>
       <Root>
```

**Comment by arnog** [comment]
Could you provide a JSFiddle demonstrating the issue? Your third case seems like it has nothing to do with MathLive, but perhaps I'm missing something?

The payload of the 'input' event is the value of the mathfield. It looks like you're expecting it to be an object literal with a `target` property which has a `value` property. So, change your code to:        ```
v-on:input="$emit('input', $event)"
```

**Comment by leontepe** [comment]
@arnog I meant to use `<mathlive-mathfield>` tag instead of `<input>` there, fixed it now.

I tried out your code change and it works now. I have to be frank though, I don't really understand what's going on here in terms of Vue, so I guess I should've looked into it a little bit more before posting this issue. Since it worked with `<input>` I supposed it's a problem with the Vue wrapper.

I don't know what exactly `$event` represents in this context and how it encapsulates the new value that the parent needs to know about to update it. I guess I will look further into this to try to understand your solution.

Thanks a lot for your help 👍

**Comment by arnog** [comment]
'input' is the name of an event. There's nothing special about it. The '<input>' component sends an 'input' event when the user inputs something. The payload (argument) of that an is an '$event' object, from which you can retrieve the value of the input field.

The '<mathlive-mathfield>' component sends an event also named 'input', but the payload of that event is directly the value that has been entered.

Hope this helps. Good luck!
