### ISSUE TITLE
TypeError: "this.element.children is undefined" using nuxtjs

### ISSUE THREAD

**Issue by leerobert** [arnog/vue-mathlive#2]
## Issue
When attempting to implement the mathlive component within nuxtjs, I get the following issue:

![alt text](https://i.imgur.com/7p7JMzI.png)

## Reproduce
1. `git clone https://github.com/leerobert/nuxt-mathlive.git` 
1. `npm install && npm run dev` 
1. navigate to `localhost:3000`

PS: amazing work with the math keyboard.

**Comment by leerobert** [comment]
Check out the component branch... I do the injection of `$mathlive` within a plugin and copy your `Mathfield` component exactly and it all seems to work. 

Any ideas here?

**Comment by arnog** [comment]
I believe you are getting a warning before this error:
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```

You need to modify your nuxt configuration by adding:
```
    extend(config, ctx) {
      config.resolve.alias["vue"] = "vue/dist/vue.common";
    },
```
You also need to either reference the fonts folder in a CDN or copy the fonts folder from the `mathlive/dist/fonts` directory in `node_modules`. To reference the CDN fonts folder, specify the `fontDirectory` config option like so:
```html
      <mathlive-mathfield
        id="mf"
        ref="mathfield"
        v-model="formula"
        :config="{smartFence:false, fontsDirectory:'https://unpkg.com/mathlive/dist/fonts'}"
        :on-keystroke="displayKeystroke"
        @focus="ping"
      >
```
