### ISSUE TITLE
Mathfield doesn't render

### ISSUE THREAD

**Issue by bvergara87** [arnog/vue-mathlive#21]
The elements appear to be in the inspector, however the mathlive field is not on the page. I basically used the example code on the repo README

`   <mathlive-mathfield
                id='mf'
                ref="mathfield"
                :config="{smartFence:false}"
                @focus="ping"
                :on-keystroke="displayKeystroke"
                v-model="formula">
                         f(x)=
       </mathlive-mathfield>
`

Also, for some odd reason, I also start getting the following error pertaining to the config

`vue.esm.js?bcea:628 [Vue warn]: Error in callback for watcher "config": "TypeError: Cannot read property '$setConfig' of undefined`

Any ideas?

**Comment by arnog** [comment]
Sorry, no idea. Might be some configuration issue. Closing, but please reopen if that's still a problem for you and share a CodePen or JSFiddle to debug the problem.
