### ISSUE TITLE
Unable run basic example

### ISSUE THREAD

**Issue by mohitsehgal** [arnog/vue-mathlive#22]
I tried to run the basic example given. It doesn't run. I am getting this weird error.  Has anybody got success in using this lib?

![image](https://user-images.githubusercontent.com/1757104/90277874-050cdd80-de84-11ea-8ded-7c27dcb30ff6.png)

**Comment by arnog** [comment]
It seems to be working now. Closing, but please reopen if that's still a problem for you.

**Comment by BruhJerem** [comment]
I still have this problem.
in main.js

```
import MathLive from 'mathlive/dist/mathlive';
import Mathfield from 'mathlive/dist/vue-mathlive.mjs';
Vue.use(Mathfield, MathLive);
```

In my component

```
<mathlive-mathfield id="mf" ref="mathfield" :config="{smartFence:false}" v-on:focus="ping"
            :on-keystroke="displayKeystroke" v-model="formula">f(x)=</mathlive-mathfield>
```

`TypeError: Cannot read property '0' of undefined`

**Comment by arnog** [comment]
This repo was pointing to an older version of Mathlive. It has been updated now. I wasn't able to get exactly the same error you reported, but I hope that this update fixes it. If it doesn't please comment and reopen.
