### ISSUE TITLE
Unable to render field

### ISSUE THREAD

**Issue by mohitsehgal** [arnog/vue-mathlive#23]
i did all the steps in this demo. Dependencies had same version. Still doesnt work. Console shows no error. Except Fonts are not loading correctly

**Comment by arnog** [comment]
Do you have the code that you're trying to run somewhere, like in a codepen for example?
And I assume this is the same issue as #22?

**Comment by arnog** [comment]
It seems to be working now. Closing, but please reopen if that's still a problem for you.
