### ISSUE TITLE
Possible to configure the fonts directory

### ISSUE THREAD

**Issue by LegendaryZReborn** [arnog/vue-mathlive#26]
Is it possible to configure the fonts directory? We can do this with the MathLive.makeMathField.

**Comment by arnog** [comment]
Yes, you can set the `fontsDirectory` config option, or any other option, when setting up the Vue view:
```html
    <mathlive-mathfield id="mf" ref="mathfield" :config="{smartFence:false, fontsDirectory:' ../fonts'}" @focus="ping"
```
