### ISSUE TITLE
Cannot get offSetWidth with frac or exponent

### ISSUE THREAD

**Issue by DungnvKaopiz** [arnog/vue-mathlive#79]
i need to get the offSetWidth when add frac on keyboard so i could scale the font size to fit the box
![image](https://user-images.githubusercontent.com/85537564/201561163-ef47fa14-1563-4c4f-a4e6-e0863b002c0c.png)
but the frac just can't get it, here's some code:

`onInput() {
      this.$nextTick(() => {
        this.scaleFontSize();
      });
    },`

```
    scaleFontSize() {
      const el = document.getElementById("mf");
      const currentFontSize = parseFloat(window.getComputedStyle(el).fontSize);
      while (el.offsetWidth >= el.parentElement.offsetWidth) {
        el.style.fontSize = currentFontSize - 1 + "px";
        this.scaleFontSize();
      }
    },
```
this works with numbers but not frac or exponent

**Comment by DungnvKaopiz** [comment]
i think the problem is more about the latex

**Comment by arnog** [comment]
I'm not sure I understand what the problem is exactly. Are you saying that `offsetWidth` does not have the value you expect when the  mathfield contains a fraction? What style do you have applied to the mathfield? What does you DOM look like?

**Comment by DungnvKaopiz** [comment]
i fingure it out, you need to wait for the convert done to get the offsetWidth
`window.MathJax.Hub.Queue(["Typeset", window.MathJax.Hub, el], () => {
//do something
}`
